CREATE TABLE posts(
id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
body TEXT NOT NULL,
time_date VARCHAR(50) NOT NULL,
time_clock VARCHAR(50) NOT NULL
);

CREATE TABLE ideas(
id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
body TEXT NOT NULL,
time_date VARCHAR(50) NOT NULL,
time_clock VARCHAR(50) NOT NULL
);
